### ISSUE TITLE
Create a README and TODO

### ISSUE THREAD

**Issue by boghison** [mozilla/webdriver-rust#9]
This is very important for people interested in (contributing to) the library. Also, #7

**Comment by detro** [comment]
I agree. I'm trying to make sense of the codebase, so that I can work out how to start a couple of tests and see how things are wired together. But it seems like the fundamental (like `WebDriver` object) are not easy to reach.

For example, I was expecting to find the "entry points" in the `lib.rs` file.
There are some things exposed, but they are objects I'd expect to never have to touch directly (like a `WebDriverCommand`).

I believe Rust has the right stuff to succeed in taking over C++ (will take some years), and I definitely want to put the learning curve to good use. And contributing to this would be great!

**Comment by Michael-F-Bryan** [comment]
It'd be really nice if someone who's more familiar with the library could write up a README. 

I'm wanting to use this library but as it stands I have no idea where to start. Even a short couple dozen lines with a "hello world"-type example would be great to show people the basic usage for this library.

**Comment by jgraham** [comment]
What are you trying to use it for? This library is low-level protocol bits aimed at implementing a WebDriver server ("remote end"). Whilst you probably could use it for a client ("local end") no design effort has gone into that use case so far.

**Comment by Michael-F-Bryan** [comment]
Ah I see. This is the first thing that pops up in google when you search for "[rust selenium webdriver][google_search]", so I thought it was a library which you can use to control a browser for doing things like testing or automation.

It sounds like you're doing the server side, whereas what I'm more looking for is a rust client that would talk to your server.

[google_search]: https://www.google.com.au/search?q=rust+selenium+webdriver

**Comment by detro** [comment]
@jgraham can I advice you guys to add a README to explain what this ISN'T?

This is at least the 2nd issue I see asking for the same kind of info.

Unfortunately Google is not helping, but you kinda put this out on GitHub with little more than a title: of course ppl are going to think this is a usable client library. Rust is getting on fire!

**Comment by Xaeroxe23** [comment]
https://github.com/mozilla/webdriver-rust/pull/54 Should help mitigate the flow of people coming here expecting a client library.

**Comment by andreastt** [comment]
This was fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1368265. You can see the README at https://hg.mozilla.org/mozilla-central/file/tip/testing/webdriver/README.md.
